### ISSUE TITLE
Drive link in youtube video not working

### ISSUE THREAD

**Issue by mchusma** [pdbuzzboard/pdbuzzboard#1]
Thanks so much for doing this! I am a developer and have built some robots as a hobbiest. I am building a set of these for my mother, who has Parkinsons. 

The google drive link in the youtube video does not work, it just shows: https://drive.google.com/drive/folder..., can you add that link to the README?

My plan is to record myself going through the process and document it as well as I can, so it can be a second resource to people trying to build these. But you did an amazing job pulling this together and documenting so far, better than 99% of projects I have implemented so far. Thanks and I will keep you posted on progress.

**Comment by pdbuzzboard** [comment]
I will add it to the readme.  The link is here: 
https://drive.google.com/drive/folders/1NHxUHjh44w7PxyNFWLYMgC35SzOBo1Ti?usp=share_link <https://drive.google.com/drive/folders/1NHxUHjh44w7PxyNFWLYMgC35SzOBo1Ti?usp=share_link>

Let me know how I can help.  I look forward to the video.

**Comment by twolips** [comment]
Chris, pdbuzzboard, I agree about the documentation, very well done.One addition: For me the version with the arduino nano worked very well,but I only realized after ordering also normal arduino+case+shields, thatI will not need those... Maybe at some time we can have split parts-list for each version ?And I#d be happy to provide amazon.europe links to parts I used.pdbuzzboard, do you want us to add our infos to gdrive/github, like addl pictures, partslinks etc ?Regards ArndAm 20.03.2023 um 01:07 schrieb pdbuzzboard ***@***.***>:﻿
I will add it to the readme.  The link is here: 
https://drive.google.com/drive/folders/1NHxUHjh44w7PxyNFWLYMgC35SzOBo1Ti?usp=share_link <https://drive.google.com/drive/folders/1NHxUHjh44w7PxyNFWLYMgC35SzOBo1Ti?usp=share_link>

Let me know how I can help.  I look forward to the video.

**Comment by mchusma** [comment]
I ordered everything! We are hoping to get it all built within a week, and will keep you posted. Thank you again!

**Comment by pdbuzzboard** [comment]
Excellent!  I hope you have anywhere near the benefits that we have had.

Let me know if you have any questions.

**Comment by twolips** [comment]
Chris, were you successful? What effects on symptoms do you see/experience ?

I built the gloves ok, but unfortunately do not see any effect after 7d of
4h+ application

Viele Grüße
Arnd


Am Mo., 20. März 2023 um 02:57 Uhr schrieb Chris Hawkins <
***@***.***>:

**Comment by pdbuzzboard** [comment]
what pulse time are you using?  Have you tried the 167?
